// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CatalogService.Data.Migrations
{
    public partial class SeedProducts : Migration
    {
        // metadata file left intentionally minimal for the hand-authored migration
    }
}
