// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CatalogService.Data.Migrations
{
    public partial class SeedProducts : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "Products",
                columns: new[] { "Id", "CreatedAt", "Description", "IsActive", "IsDeleted", "Name", "Price", "Stock", "UpdatedAt", "Xmin" },
                values: new object[,]
                {
                    { new Guid("11111111-0000-0000-0000-000000000001"), DateTime.Parse("2025-06-13T00:00:00Z"), "Comfortable cotton t-shirt", true, false, "Red T-Shirt", 19.99m, 100, null, 0u },
                    { new Guid("11111111-0000-0000-0000-000000000002"), DateTime.Parse("2025-06-13T00:00:00Z"), "Slim fit denim jeans", true, false, "Blue Jeans", 49.50m, 50, null, 0u },
                    { new Guid("11111111-0000-0000-0000-000000000003"), DateTime.Parse("2025-06-13T00:00:00Z"), "Lightweight running shoes", true, false, "Running Shoes", 89.00m, 30, null, 0u },
                    { new Guid("11111111-0000-0000-0000-000000000004"), DateTime.Parse("2025-06-13T00:00:00Z"), "Ceramic mug 350ml", true, false, "Coffee Mug", 9.25m, 200, null, 0u },
                    { new Guid("11111111-0000-0000-0000-000000000005"), DateTime.Parse("2025-06-13T00:00:00Z"), "Ergonomic wireless mouse", true, false, "Wireless Mouse", 29.99m, 75, null, 0u }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "Products",
                keyColumn: "Id",
                keyValues: new object[]
                {
                    new Guid("11111111-0000-0000-0000-000000000001"),
                    new Guid("11111111-0000-0000-0000-000000000002"),
                    new Guid("11111111-0000-0000-0000-000000000003"),
                    new Guid("11111111-0000-0000-0000-000000000004"),
                    new Guid("11111111-0000-0000-0000-000000000005")
                });
        }
    }
}
