// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using CatalogService.Data;

namespace CatalogService.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CatalogService.Domain.Entities.Product", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd();

                b.Property<DateTime>("CreatedAt");

                b.Property<DateTime?>("UpdatedAt");

                b.Property<bool>("IsDeleted");

                b.Property<string>("Name").IsRequired();

                b.Property<string>("Description").IsRequired();

                b.Property<decimal>("Price");

                b.Property<int>("Stock");

                b.Property<bool>("IsActive");

                b.Property<uint>("Xmin").HasColumnName("xmin");

                b.HasKey("Id");

                b.ToTable("Products");
            });
        }
    }
}
