// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using NotificationService.Data;

namespace NotificationService.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("NotificationService.Domain.Entities.Notification", b =>
            {
                b.Property<Guid>("OrderId");

                b.Property<string>("Channel").IsRequired().HasMaxLength(50);

                b.Property<string>("Message").IsRequired();

                b.HasKey("OrderId");

                b.ToTable("Notifications");
            });
        }
    }
}
