// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using OrderService.Data;

namespace OrderService.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("OrderService.Domain.Entities.Order", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd();

                b.Property<DateTime>("CreatedAt");

                b.Property<DateTime?>("UpdatedAt");

                b.Property<bool>("IsDeleted");

                b.Property<string>("CustomerEmail").IsRequired().HasMaxLength(256);

                b.Property<string>("CustomerTelNumber");

                b.Property<int>("Status");

                b.HasKey("Id");

                b.ToTable("Orders");
            });

            modelBuilder.Entity("OrderService.Domain.Entities.OrderItem", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd();

                b.Property<DateTime>("CreatedAt");

                b.Property<DateTime?>("UpdatedAt");

                b.Property<bool>("IsDeleted");

                b.Property<Guid>("OrderId");

                b.Property<Guid>("ProductId");

                b.Property<string>("ProductName").IsRequired().HasMaxLength(256);

                b.Property<int>("Quantity");

                b.Property<decimal>("UnitPrice");

                b.HasKey("Id");

                b.HasIndex("OrderId");

                b.ToTable("OrderItems");
            });
        }
    }
}
